# Generated by Django 3.2.5 on 2022-08-05 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220801_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toda',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('64d272fc-6965-46b7-84ec-f99313a92d34'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TimingTodo',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('64d272fc-6965-46b7-84ec-f99313a92d34'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('timing', models.DateTimeField()),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
