# Generated by Django 3.2.5 on 2022-08-05 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220805_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='timing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('53c5bc4a-7900-4bac-9f2a-c527a1a92cde'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toda',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('53c5bc4a-7900-4bac-9f2a-c527a1a92cde'), editable=False, primary_key=True, serialize=False),
        ),
    ]
